### ISSUE TITLE
workdir.py is in .gitignore and unable to use workdir

### ISSUE THREAD

**Issue by Riaz123** [big-data-lab-team/accident-prediction-montreal#18]
unable to import  : from workdir import workdir
I tried os.path.join(os.getcwd(), 'data/matches_accident-road.parquet')
but I get "TypeError: unsupported operand type(s) for +: 'module' and 'str'".
tries absolute path as well, but no luck.

**Comment by hantoine** [comment]
This error occurs because most main scripts use the variable workdir from a file workdir.py in the source folder. This is a configuration file used to specify the work directory used by all the scripts. The work directory is the directory in which the data directory will be created/used.

This file was not committed to git because different developers used different configurations.
I have added a default workdir configuration that uses the current directory. This will solve the problem you had.
